theme: minima
title: ctdhr / infosec
author: ctdhr
description: A blue-teamer's life in IT security


show_excerpts: true

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: daherk
github_username:  ctdhr

minima:
  date_format: "%b %-d, %Y"

header_pages:
  - index.md
  - pages/tips.md
  - pages/about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
